version: "3"

services:
  rabbitmq:
    container_name: rabbitserver
    hostname: rabbit
    image: rabbit-server-custom
    volumes:
      - "./data:/var/lib/rabbitmq/mnesia/"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge
